// Generated by CoffeeScript 1.6.3
(function() {
  document.getElementById("nameform").onsubmit = function() {
    var name;
    name = document.getElementById("name").value;
    alert("こんにちは、" + name + "さん");
    return false;
  };

}).call(this);

/*
//@ sourceMappingURL=sample02.map
*/
